#!/usr/bin/env zsh
# ------------------------------------------------------------------------------------------
# Description
#   ZLE widget that shows dots while completion is running.
#
# Usage
#   Bind it to ".":
#     autoload expand-or-complete-with-dots
#     zle -N expand-or-complete-with-dots
#     bindkey "^I" expand-or-complete-with-dots
# ------------------------------------------------------------------------------------------

echo -n '…'
zle expand-or-complete
zle redisplay

