#!/bin/bash

if [ -z `which meld` ] ; then
    zenity --error --text="meld not found!

Please install meld."
    exit 1
fi

if [ $# -eq 0 ] ; then
    meld .
    exit
fi

if [ $# -gt 3 ] ; then
    zenity --error --text="meld supports maximum 3 arguments!"
    exit 2
fi

IFS=$'\n'

meld $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
