#!/usr/bin/env bash

# FIXME Do not declare Dropbox home here.
DROPBOX_HOME=~/documents/Dropbox

# Check $DROPBOX_HOME is set.
if [[ ! -d $DROPBOX_HOME ]]; then
  zenity --error --text="The \$DROPBOX_HOME variable is not set to a valid folder."
  exit 1
fi

# Copy the stuff to the Dropbox folder.
cp -r $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS $DROPBOX_HOME/

# Show a notification.
notify-send --icon=/usr/share/icons/hicolor/48x48/apps/dropbox.png "File sent to Dropbox."
