#!/usr/bin/env zsh
# ------------------------------------------------------------------------------------------
# Description
#   A completer that does not complete anything but forces rehash.
# ------------------------------------------------------------------------------------------

(( CURRENT == 1 )) && rehash
return 1
