#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Description
#   ~/.bashrc: executed by bash(1) for non-login shells.
# ------------------------------------------------------------------------------


# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Just load ~/.bash_profile if it exists.
if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi
