#!/bin/sh
# ------------------------------------------------------------------------------
# Description
#   Daemon script for tircd on Ubuntu.
#   See http://code.google.com/p/tircd/.
#
# Usage
#   Drop it in /etc/init.d and run:
#     $ update-rc.d tircd defaults
# ------------------------------------------------------------------------------

### BEGIN INIT INFO
# Provides:          twitter
# Required-Start:    $local_fs $remote_fs $syslog $named $network $time
# Required-Stop:     $local_fs $remote_fs $syslog $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop the tircd
# Description:       tircd is a twitter-irc gateway
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/tircd
NAME=tircd

test -f $DAEMON || exit 0

set -e

case "$1" in
	start)
		echo "Starting $NAME."
		start-stop-daemon --start \
											--background \
		                  --quiet \
		                  --pidfile /var/run/tircd/$NAME.pid \
		                  --exec $DAEMON
		;;
	stop)
		echo "Stopping $NAME."
		start-stop-daemon --stop \
		                  --quiet \
		                  --pidfile /var/run/tircd/$NAME.pid \
		                  --oknodo \
		                  --exec /usr/bin/python
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
	;;
esac

exit 0
